# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rds_anticollision/emergency_stop_root_cause.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rds_anticollision.msg

class emergency_stop_root_cause(genpy.Message):
  _md5sum = "d411f9af8dac62ba702700d1fd92b8e7"
  _type = "rds_anticollision/emergency_stop_root_cause"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """error[] causes

# Vehicle Context when fired
float32 speed

================================================================================
MSG: rds_anticollision/error
# Generic error
# Value field equals 0 means no error (whatever category is set to)
uint32 category
int32 value
"""
  __slots__ = ['causes','speed']
  _slot_types = ['rds_anticollision/error[]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       causes,speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(emergency_stop_root_cause, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.causes is None:
        self.causes = []
      if self.speed is None:
        self.speed = 0.
    else:
      self.causes = []
      self.speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.causes)
      buff.write(_struct_I.pack(length))
      for val1 in self.causes:
        _x = val1
        buff.write(_get_struct_Ii().pack(_x.category, _x.value))
      _x = self.speed
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.causes is None:
        self.causes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.causes = []
      for i in range(0, length):
        val1 = rds_anticollision.msg.error()
        _x = val1
        start = end
        end += 8
        (_x.category, _x.value,) = _get_struct_Ii().unpack(str[start:end])
        self.causes.append(val1)
      start = end
      end += 4
      (self.speed,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.causes)
      buff.write(_struct_I.pack(length))
      for val1 in self.causes:
        _x = val1
        buff.write(_get_struct_Ii().pack(_x.category, _x.value))
      _x = self.speed
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.causes is None:
        self.causes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.causes = []
      for i in range(0, length):
        val1 = rds_anticollision.msg.error()
        _x = val1
        start = end
        end += 8
        (_x.category, _x.value,) = _get_struct_Ii().unpack(str[start:end])
        self.causes.append(val1)
      start = end
      end += 4
      (self.speed,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Ii = None
def _get_struct_Ii():
    global _struct_Ii
    if _struct_Ii is None:
        _struct_Ii = struct.Struct("<Ii")
    return _struct_Ii
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
