(cl:in-package rds_perception_msgs-msg)
(cl:export '(ID-VAL
          ID
          STATE-VAL
          STATE
          COVARIANCE-VAL
          COVARIANCE
          LABEL-VAL
          LABEL
          EXTENT-VAL
          EXTENT
          UPTIME-VAL
          UPTIME
          MISSTIME-VAL
          MISSTIME
          BOX_CENTER_X-VAL
          BOX_CENTER_X
          BOX_CENTER_Y-VAL
          BOX_CENTER_Y
          AXIS_1X-VAL
          AXIS_1X
          AXIS_1Y-VAL
          AXIS_1Y
          AXIS_2X-VAL
          AXIS_2X
          AXIS_2Y-VAL
          AXIS_2Y
          DIM1-VAL
          DIM1
          DIM2-VAL
          DIM2
))