(cl:defpackage rds_conti_radar_object_list_msgs-msg
  (:use )
  (:export
   "<DYNAMICPROPERTY>"
   "DYNAMICPROPERTY"
   "<LDELTAQUAL>"
   "LDELTAQUAL"
   "<MSGHEADER>"
   "MSGHEADER"
   "<OBJPROVIDEDKINEMATICSTATES>"
   "OBJPROVIDEDKINEMATICSTATES"
   "<OBJSTATE>"
   "OBJSTATE"
   "<RADAROBJECT>"
   "RADAROBJECT"
   "<RADAROBJECTLIST>"
   "RADAROBJECTLIST"
   "<SENSORMSGHEADER>"
   "SENSORMSGHEADER"
   "<SIGNALSTATUS>"
   "SIGNALSTATUS"
   "<TIME>"
   "TIME"
   "<TIMESTAMPSOURCE>"
   "TIMESTAMPSOURCE"
   "<TIMESTAMPSYNCSTATE>"
   "TIMESTAMPSYNCSTATE"
  ))

