(cl:in-package rds_conti_radar_object_list_msgs-msg)
(cl:export '(OBJID-VAL
          OBJID
          INTERNALID-VAL
          INTERNALID
          DISTX-VAL
          DISTX
          DISTY-VAL
          DISTY
          VRELX-VAL
          VRELX
          VRELY-VAL
          VRELY
          ARELX-VAL
          ARELX
          ARELY-VAL
          ARELY
          DISTXSTD-VAL
          DISTXSTD
          DISTYSTD-VAL
          DISTYSTD
          VRELXSTD-VAL
          VRELXSTD
          VRELYSTD-VAL
          VRELYSTD
          ARELXSTD-VAL
          ARELXSTD
          ARELYSTD-VAL
          ARELYSTD
          LDELTAX_LEFT-VAL
          LDELTAX_LEFT
          LDELTAX_MID-VAL
          LDELTAX_MID
          LDELTAX_RIGHT-VAL
          LDELTAX_RIGHT
          LDELTAY_LEFT-VAL
          LDELTAY_LEFT
          LDELTAY_MID-VAL
          LDELTAY_MID
          LDELTAY_RIGHT-VAL
          LDELTAY_RIGHT
          LDELTAQUAL-VAL
          LDELTAQUAL
          RCS-VAL
          RCS
          PROBOFEXISTENCE-VAL
          PROBOFEXISTENCE
          LIFECYCLES-VAL
          LIFECYCLES
          DYNAMICPROPERTY-VAL
          DYNAMICPROPERTY
          OBJSTATE-VAL
          OBJSTATE
          OBJMEASUREDSOURCES-VAL
          OBJMEASUREDSOURCES
          VABSX-VAL
          VABSX
          VABSY-VAL
          VABSY
          AABSX-VAL
          AABSX
          AABSY-VAL
          AABSY
          VABSXSTD-VAL
          VABSXSTD
          VABSYSTD-VAL
          VABSYSTD
          AABSXSTD-VAL
          AABSXSTD
          AABSYSTD-VAL
          AABSYSTD
          ORIENTATION-VAL
          ORIENTATION
          ORIENTATIONSTD-VAL
          ORIENTATIONSTD
))