(cl:defpackage rds_anticollision-msg
  (:use )
  (:export
   "<ABILITY>"
   "ABILITY"
   "<DRIVE_MODE>"
   "DRIVE_MODE"
   "<EMERGENCY_STOP_ROOT_CAUSE>"
   "EMERGENCY_STOP_ROOT_CAUSE"
   "<ERROR>"
   "ERROR"
   "<MOTION>"
   "MOTION"
   "<MSG_VEHICLE_STATE_COMMON>"
   "MSG_VEHICLE_STATE_COMMON"
   "<SAFETY_CHAIN_STATE>"
   "SAFETY_CHAIN_STATE"
   "<START_MISSION_STATE>"
   "START_MISSION_STATE"
  ))

