# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nav_ross/nav_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class nav_msg(genpy.Message):
  _md5sum = "18581dec57d2b4d9e4f4a5bc2f5e3e17"
  _type = "nav_ross/nav_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 range_resolution
uint16 AzimuthSamples
uint16 EncoderSize
uint16 BinSize
uint16 RangeInBins
uint16 ExpectedRotationRate"""
  __slots__ = ['range_resolution','AzimuthSamples','EncoderSize','BinSize','RangeInBins','ExpectedRotationRate']
  _slot_types = ['float64','uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       range_resolution,AzimuthSamples,EncoderSize,BinSize,RangeInBins,ExpectedRotationRate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(nav_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.range_resolution is None:
        self.range_resolution = 0.
      if self.AzimuthSamples is None:
        self.AzimuthSamples = 0
      if self.EncoderSize is None:
        self.EncoderSize = 0
      if self.BinSize is None:
        self.BinSize = 0
      if self.RangeInBins is None:
        self.RangeInBins = 0
      if self.ExpectedRotationRate is None:
        self.ExpectedRotationRate = 0
    else:
      self.range_resolution = 0.
      self.AzimuthSamples = 0
      self.EncoderSize = 0
      self.BinSize = 0
      self.RangeInBins = 0
      self.ExpectedRotationRate = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d5H().pack(_x.range_resolution, _x.AzimuthSamples, _x.EncoderSize, _x.BinSize, _x.RangeInBins, _x.ExpectedRotationRate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.range_resolution, _x.AzimuthSamples, _x.EncoderSize, _x.BinSize, _x.RangeInBins, _x.ExpectedRotationRate,) = _get_struct_d5H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d5H().pack(_x.range_resolution, _x.AzimuthSamples, _x.EncoderSize, _x.BinSize, _x.RangeInBins, _x.ExpectedRotationRate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.range_resolution, _x.AzimuthSamples, _x.EncoderSize, _x.BinSize, _x.RangeInBins, _x.ExpectedRotationRate,) = _get_struct_d5H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d5H = None
def _get_struct_d5H():
    global _struct_d5H
    if _struct_d5H is None:
        _struct_d5H = struct.Struct("<d5H")
    return _struct_d5H
