// Generated by gencpp from file rds_msgs/localization_gnss.msg
// DO NOT EDIT!


#ifndef RDS_MSGS_MESSAGE_LOCALIZATION_GNSS_H
#define RDS_MSGS_MESSAGE_LOCALIZATION_GNSS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseWithCovariance.h>
#include <rds_msgs/localization_gnss_detail.h>

namespace rds_msgs
{
template <class ContainerAllocator>
struct localization_gnss_
{
  typedef localization_gnss_<ContainerAllocator> Type;

  localization_gnss_()
    : header()
    , pose()
    , detail()  {
    }
  localization_gnss_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , detail(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::rds_msgs::localization_gnss_detail_<ContainerAllocator>  _detail_type;
  _detail_type detail;





  typedef boost::shared_ptr< ::rds_msgs::localization_gnss_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rds_msgs::localization_gnss_<ContainerAllocator> const> ConstPtr;

}; // struct localization_gnss_

typedef ::rds_msgs::localization_gnss_<std::allocator<void> > localization_gnss;

typedef boost::shared_ptr< ::rds_msgs::localization_gnss > localization_gnssPtr;
typedef boost::shared_ptr< ::rds_msgs::localization_gnss const> localization_gnssConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rds_msgs::localization_gnss_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rds_msgs::localization_gnss_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rds_msgs::localization_gnss_<ContainerAllocator1> & lhs, const ::rds_msgs::localization_gnss_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.detail == rhs.detail;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rds_msgs::localization_gnss_<ContainerAllocator1> & lhs, const ::rds_msgs::localization_gnss_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rds_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rds_msgs::localization_gnss_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rds_msgs::localization_gnss_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_msgs::localization_gnss_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_msgs::localization_gnss_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_msgs::localization_gnss_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_msgs::localization_gnss_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rds_msgs::localization_gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f5e4523115c22b0b204c6ef79abd94a";
  }

  static const char* value(const ::rds_msgs::localization_gnss_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f5e4523115c22b0ULL;
  static const uint64_t static_value2 = 0xb204c6ef79abd94aULL;
};

template<class ContainerAllocator>
struct DataType< ::rds_msgs::localization_gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rds_msgs/localization_gnss";
  }

  static const char* value(const ::rds_msgs::localization_gnss_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rds_msgs::localization_gnss_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/PoseWithCovariance pose\n"
"localization_gnss_detail detail\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: rds_msgs/localization_gnss_detail\n"
"uint16 date_week\n"
"uint32 date_millisecs\n"
"\n"
"gnss_mode mode\n"
"float32 correction_age\n"
"\n"
"uint8 num_sat_tracked\n"
"uint8 num_sat_used_l1\n"
"uint8 num_sat_used_l1l2\n"
"\n"
"================================================================================\n"
"MSG: rds_msgs/gnss_mode\n"
"int8 MODE_UNKNOWN = -1\n"
"int8 MODE_SINGLE = 0\n"
"int8 MODE_DIFF = 1\n"
"int8 MODE_RTK_FLOAT = 2\n"
"int8 MODE_RTK_INT = 3\n"
"int8 MODE_PPP_CONVERGING = 4\n"
"int8 MODE_PPP = 5\n"
"int8 mode\n"
"\n"
;
  }

  static const char* value(const ::rds_msgs::localization_gnss_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rds_msgs::localization_gnss_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct localization_gnss_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rds_msgs::localization_gnss_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rds_msgs::localization_gnss_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "detail: ";
    s << std::endl;
    Printer< ::rds_msgs::localization_gnss_detail_<ContainerAllocator> >::stream(s, indent + "  ", v.detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDS_MSGS_MESSAGE_LOCALIZATION_GNSS_H
