// Generated by gencpp from file rds_msgs/safety_chain_state.msg
// DO NOT EDIT!


#ifndef RDS_MSGS_MESSAGE_SAFETY_CHAIN_STATE_H
#define RDS_MSGS_MESSAGE_SAFETY_CHAIN_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rds_msgs
{
template <class ContainerAllocator>
struct safety_chain_state_
{
  typedef safety_chain_state_<ContainerAllocator> Type;

  safety_chain_state_()
    : state(0)  {
    }
  safety_chain_state_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_ACTIVE)
  #undef STATE_ACTIVE
#endif
#if defined(_WIN32) && defined(STATE_DISABLED)
  #undef STATE_DISABLED
#endif
#if defined(_WIN32) && defined(STATE_FAILSOFT)
  #undef STATE_FAILSOFT
#endif

  enum {
    STATE_ACTIVE = 0u,
    STATE_DISABLED = 1u,
    STATE_FAILSOFT = 2u,
  };


  typedef boost::shared_ptr< ::rds_msgs::safety_chain_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rds_msgs::safety_chain_state_<ContainerAllocator> const> ConstPtr;

}; // struct safety_chain_state_

typedef ::rds_msgs::safety_chain_state_<std::allocator<void> > safety_chain_state;

typedef boost::shared_ptr< ::rds_msgs::safety_chain_state > safety_chain_statePtr;
typedef boost::shared_ptr< ::rds_msgs::safety_chain_state const> safety_chain_stateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rds_msgs::safety_chain_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rds_msgs::safety_chain_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rds_msgs::safety_chain_state_<ContainerAllocator1> & lhs, const ::rds_msgs::safety_chain_state_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rds_msgs::safety_chain_state_<ContainerAllocator1> & lhs, const ::rds_msgs::safety_chain_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rds_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rds_msgs::safety_chain_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_msgs::safety_chain_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_msgs::safety_chain_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c854c67ecd4d86925912568f00ec3d5";
  }

  static const char* value(const ::rds_msgs::safety_chain_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c854c67ecd4d869ULL;
  static const uint64_t static_value2 = 0x25912568f00ec3d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rds_msgs/safety_chain_state";
  }

  static const char* value(const ::rds_msgs::safety_chain_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STATE_ACTIVE = 0\n"
"uint8 STATE_DISABLED = 1\n"
"uint8 STATE_FAILSOFT = 2\n"
"\n"
"uint8 state\n"
;
  }

  static const char* value(const ::rds_msgs::safety_chain_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct safety_chain_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rds_msgs::safety_chain_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rds_msgs::safety_chain_state_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDS_MSGS_MESSAGE_SAFETY_CHAIN_STATE_H
