// Generated by gencpp from file rds_conti_radar_object_list_msgs/MsgHeader.msg
// DO NOT EDIT!


#ifndef RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_MSGHEADER_H
#define RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_MSGHEADER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rds_conti_radar_object_list_msgs/Time.h>
#include <rds_conti_radar_object_list_msgs/TimeStampSource.h>
#include <rds_conti_radar_object_list_msgs/TimeStampSyncState.h>

namespace rds_conti_radar_object_list_msgs
{
template <class ContainerAllocator>
struct MsgHeader_
{
  typedef MsgHeader_<ContainerAllocator> Type;

  MsgHeader_()
    : Seq(0)
    , stamp()
    , Timestamp_source()
    , TimeStamp_sync_state()  {
    }
  MsgHeader_(const ContainerAllocator& _alloc)
    : Seq(0)
    , stamp(_alloc)
    , Timestamp_source(_alloc)
    , TimeStamp_sync_state(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _Seq_type;
  _Seq_type Seq;

   typedef  ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator>  _stamp_type;
  _stamp_type stamp;

   typedef  ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator>  _Timestamp_source_type;
  _Timestamp_source_type Timestamp_source;

   typedef  ::rds_conti_radar_object_list_msgs::TimeStampSyncState_<ContainerAllocator>  _TimeStamp_sync_state_type;
  _TimeStamp_sync_state_type TimeStamp_sync_state;





  typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> const> ConstPtr;

}; // struct MsgHeader_

typedef ::rds_conti_radar_object_list_msgs::MsgHeader_<std::allocator<void> > MsgHeader;

typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::MsgHeader > MsgHeaderPtr;
typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::MsgHeader const> MsgHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator1> & lhs, const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator2> & rhs)
{
  return lhs.Seq == rhs.Seq &&
    lhs.stamp == rhs.stamp &&
    lhs.Timestamp_source == rhs.Timestamp_source &&
    lhs.TimeStamp_sync_state == rhs.TimeStamp_sync_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator1> & lhs, const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rds_conti_radar_object_list_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f65b5aa4f825d78a4a1dd55ce9d49881";
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf65b5aa4f825d78aULL;
  static const uint64_t static_value2 = 0x4a1dd55ce9d49881ULL;
};

template<class ContainerAllocator>
struct DataType< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rds_conti_radar_object_list_msgs/MsgHeader";
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#MsgHeader fields\n"
"uint32 Seq          #sequence ID: consecutively increasing ID\n"
"Time stamp\n"
"TimeStampSource Timestamp_source\n"
"TimeStampSyncState TimeStamp_sync_state\n"
"\n"
"================================================================================\n"
"MSG: rds_conti_radar_object_list_msgs/Time\n"
"#Time fields\n"
"uint32 Sec\n"
"uint32 Nsec \n"
"\n"
"================================================================================\n"
"MSG: rds_conti_radar_object_list_msgs/TimeStampSource\n"
"#MsgHeader field TimeStampSource\n"
"uint8 TIMESTAMPSOURCE_UNKNOWN_SOURCE = 0    #No information on the source at all\n"
"uint8 TIMESTAMPSOURCE_SENSOR = 1            #Timestamp is set by sensor\n"
"uint8 TIMESTAMPSOURCE_ALGO = 2              #Timestamp is set by algo\n"
"\n"
"uint8 TimeStampSource \n"
"================================================================================\n"
"MSG: rds_conti_radar_object_list_msgs/TimeStampSyncState\n"
"#MsgHeader field TimeStampSyncState\n"
"uint8 TIMESTAMPSYNCSTATE_UNKNOWN_SYNC = 0              #No information on the sync state at all\n"
"uint8 TIMESTAMPSYNCSTATE_NOT_SYNCED = 1                #timestamp is not synced at all\n"
"uint8 TIMESTAMPSYNCSTATE_SYNCED_GTC = 2                #timestamp is synced with GTC mechanism\n"
"uint8 TIMESTAMPSYNCSTATE_SYNCED_PTP = 3                #timestamp is synced with PTP mechanism\n"
"uint8 TIMESTAMPSYNCSTATE_SYNCED_REPLAY = 4             #timestamp is synced by replay mechanism\n"
"\n"
"uint8 TimeStampSyncState\n"
;
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Seq);
      stream.next(m.stamp);
      stream.next(m.Timestamp_source);
      stream.next(m.TimeStamp_sync_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rds_conti_radar_object_list_msgs::MsgHeader_<ContainerAllocator>& v)
  {
    s << indent << "Seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Seq);
    s << indent << "stamp: ";
    s << std::endl;
    Printer< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >::stream(s, indent + "  ", v.stamp);
    s << indent << "Timestamp_source: ";
    s << std::endl;
    Printer< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >::stream(s, indent + "  ", v.Timestamp_source);
    s << indent << "TimeStamp_sync_state: ";
    s << std::endl;
    Printer< ::rds_conti_radar_object_list_msgs::TimeStampSyncState_<ContainerAllocator> >::stream(s, indent + "  ", v.TimeStamp_sync_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_MSGHEADER_H
