// Generated by gencpp from file rds_conti_radar_object_list_msgs/Time.msg
// DO NOT EDIT!


#ifndef RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_TIME_H
#define RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_TIME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rds_conti_radar_object_list_msgs
{
template <class ContainerAllocator>
struct Time_
{
  typedef Time_<ContainerAllocator> Type;

  Time_()
    : Sec(0)
    , Nsec(0)  {
    }
  Time_(const ContainerAllocator& _alloc)
    : Sec(0)
    , Nsec(0)  {
  (void)_alloc;
    }



   typedef uint32_t _Sec_type;
  _Sec_type Sec;

   typedef uint32_t _Nsec_type;
  _Nsec_type Nsec;





  typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> const> ConstPtr;

}; // struct Time_

typedef ::rds_conti_radar_object_list_msgs::Time_<std::allocator<void> > Time;

typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::Time > TimePtr;
typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::Time const> TimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator1> & lhs, const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator2> & rhs)
{
  return lhs.Sec == rhs.Sec &&
    lhs.Nsec == rhs.Nsec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator1> & lhs, const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rds_conti_radar_object_list_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d25eef3a4dddf6c83752b23dcacfd7aa";
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd25eef3a4dddf6c8ULL;
  static const uint64_t static_value2 = 0x3752b23dcacfd7aaULL;
};

template<class ContainerAllocator>
struct DataType< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rds_conti_radar_object_list_msgs/Time";
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Time fields\n"
"uint32 Sec\n"
"uint32 Nsec \n"
;
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Sec);
      stream.next(m.Nsec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Time_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rds_conti_radar_object_list_msgs::Time_<ContainerAllocator>& v)
  {
    s << indent << "Sec: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Sec);
    s << indent << "Nsec: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Nsec);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_TIME_H
