// Generated by gencpp from file rds_conti_radar_object_list_msgs/TimeStampSource.msg
// DO NOT EDIT!


#ifndef RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_TIMESTAMPSOURCE_H
#define RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_TIMESTAMPSOURCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rds_conti_radar_object_list_msgs
{
template <class ContainerAllocator>
struct TimeStampSource_
{
  typedef TimeStampSource_<ContainerAllocator> Type;

  TimeStampSource_()
    : TimeStampSource(0)  {
    }
  TimeStampSource_(const ContainerAllocator& _alloc)
    : TimeStampSource(0)  {
  (void)_alloc;
    }



   typedef uint8_t _TimeStampSource_type;
  _TimeStampSource_type TimeStampSource;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TIMESTAMPSOURCE_UNKNOWN_SOURCE)
  #undef TIMESTAMPSOURCE_UNKNOWN_SOURCE
#endif
#if defined(_WIN32) && defined(TIMESTAMPSOURCE_SENSOR)
  #undef TIMESTAMPSOURCE_SENSOR
#endif
#if defined(_WIN32) && defined(TIMESTAMPSOURCE_ALGO)
  #undef TIMESTAMPSOURCE_ALGO
#endif

  enum {
    TIMESTAMPSOURCE_UNKNOWN_SOURCE = 0u,
    TIMESTAMPSOURCE_SENSOR = 1u,
    TIMESTAMPSOURCE_ALGO = 2u,
  };


  typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> const> ConstPtr;

}; // struct TimeStampSource_

typedef ::rds_conti_radar_object_list_msgs::TimeStampSource_<std::allocator<void> > TimeStampSource;

typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::TimeStampSource > TimeStampSourcePtr;
typedef boost::shared_ptr< ::rds_conti_radar_object_list_msgs::TimeStampSource const> TimeStampSourceConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator1> & lhs, const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator2> & rhs)
{
  return lhs.TimeStampSource == rhs.TimeStampSource;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator1> & lhs, const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rds_conti_radar_object_list_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fb2d134001df6f67e0a8dc8c7ddc7e6";
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fb2d134001df6f6ULL;
  static const uint64_t static_value2 = 0x7e0a8dc8c7ddc7e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rds_conti_radar_object_list_msgs/TimeStampSource";
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#MsgHeader field TimeStampSource\n"
"uint8 TIMESTAMPSOURCE_UNKNOWN_SOURCE = 0    #No information on the source at all\n"
"uint8 TIMESTAMPSOURCE_SENSOR = 1            #Timestamp is set by sensor\n"
"uint8 TIMESTAMPSOURCE_ALGO = 2              #Timestamp is set by algo\n"
"\n"
"uint8 TimeStampSource \n"
;
  }

  static const char* value(const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TimeStampSource);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeStampSource_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rds_conti_radar_object_list_msgs::TimeStampSource_<ContainerAllocator>& v)
  {
    s << indent << "TimeStampSource: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TimeStampSource);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDS_CONTI_RADAR_OBJECT_LIST_MSGS_MESSAGE_TIMESTAMPSOURCE_H
