(cl:in-package rds_foresight_camera_object_list_msgs-msg)
(cl:export '(BOUNDBOX-VAL
          BOUNDBOX
          CENTERX-VAL
          CENTERX
          CENTERY-VAL
          CENTERY
          CLASS-VAL
          CLASS
          DANGERLEVEL-VAL
          DANGERLEVEL
          DISTANCE-VAL
          DISTANCE
          ID-VAL
          ID
          ONPATH-VAL
          ONPATH
          ONROAD-VAL
          ONROAD
          POSITIONX-VAL
          POSITIONX
          POSITIONY-VAL
          POSITIONY
          POSITIONZ-VAL
          POSITIONZ
          REALHEIGHT-VAL
          REALHEIGHT
          REALWIDTH-VAL
          REALWIDTH
          RELATIVESPEED-VAL
          RELATIVESPEED
          TTC-VAL
          TTC
))